# Generated by Django 5.2.16 on 2026-07-19 07:21

import datetime
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('MEMO', 'Memorandum'), ('IND', 'Indorsement'), ('OO', 'Office Order'), ('EO', 'Executive Order')], max_length=8, verbose_name='Document type')),
                ('series_year', models.PositiveIntegerField(default=2026, verbose_name='Series year')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Leave blank to take the next number in this series.', null=True, verbose_name='Number')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='Summary or full text')),
                ('date_issued', models.DateField(default=datetime.date.today)),
                ('effectivity_date', models.DateField(blank=True, null=True)),
                ('originating_office', models.CharField(blank=True, max_length=150)),
                ('signatory', models.CharField(blank=True, max_length=150, verbose_name='Signed by')),
                ('addressee', models.CharField(blank=True, max_length=255, verbose_name='Addressed to')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated tags used by search.', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'In effect'), ('SUPERSEDED', 'Superseded'), ('REVOKED', 'Revoked'), ('ARCHIVED', 'Closed and archived')], default='ACTIVE', max_length=12)),
                ('classification', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential')], default='INTERNAL', max_length=12)),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.models.archive_upload_path, verbose_name='Scanned copy')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('physical_location', models.CharField(blank=True, help_text='Where the hard copy sits, e.g. Cabinet 3, Drawer B.', max_length=150, verbose_name='Physical file location')),
                ('indorsement_level', models.PositiveSmallIntegerField(blank=True, help_text='1 for 1st Indorsement, 2 for 2nd, and so on.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='documents.document', verbose_name='Refers to document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-series_year', 'doc_type', '-number'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to=documents.models.attachment_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.document')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Signed in'), ('LOGOUT', 'Signed out'), ('VIEW', 'Opened document'), ('DOWNLOAD', 'Downloaded file'), ('CREATE', 'Filed document'), ('UPDATE', 'Edited document'), ('DELETE', 'Removed document'), ('RESTORE', 'Restored document'), ('SEARCH', 'Ran a search'), ('USER_MANAGE', 'Managed an account'), ('DENIED', 'Access denied')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='documents.document')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type', 'series_year'], name='documents_d_doc_typ_4b58b4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['date_issued'], name='documents_d_date_is_5384a9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['subject'], name='documents_d_subject_73ff7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('doc_type', 'series_year', 'number'), name='unique_control_number'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['-timestamp'], name='documents_a_timesta_066730_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['action'], name='documents_a_action_9d0ff5_idx'),
        ),
    ]
