# Generated by Django 5.2.16 on 2026-07-19 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_office', models.CharField(max_length=150)),
                ('to_office', models.CharField(max_length=150)),
                ('action_requested', models.CharField(blank=True, help_text="e.g. 'For appropriate action', 'For your information'.", max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In transit'), ('RECEIVED', 'Received'), ('RETURNED', 'Returned to sender')], default='IN_TRANSIT', max_length=12)),
                ('due_date', models.DateField(blank=True, help_text='Expected turnaround date.', null=True)),
                ('routed_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='documents.document')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routings_received', to=settings.AUTH_USER_MODEL)),
                ('routed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routings_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-routed_at'],
                'indexes': [models.Index(fields=['document', '-routed_at'], name='documents_d_documen_97c6f9_idx'), models.Index(fields=['status'], name='documents_d_status_1769c9_idx')],
            },
        ),
    ]
