# Generated by Django 5.2.16 on 2026-07-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentrouting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentRouting',
        ),
    ]
