# Generated by Django 5.2.12 on 2026-07-20 07:43

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Signed in'), ('LOGOUT', 'Signed out'), ('VIEW', 'Opened document'), ('DOWNLOAD', 'Downloaded file'), ('CREATE', 'Filed document'), ('UPDATE', 'Edited document'), ('DELETE', 'Removed document'), ('RESTORE', 'Restored document'), ('SEARCH', 'Ran a search'), ('USER_MANAGE', 'Managed an account'), ('DENIED', 'Access denied'), ('IMPORT', 'Bulk import')], max_length=16),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.import_upload_path, verbose_name='CSV file')),
                ('status', models.CharField(choices=[('PENDING', 'Uploaded'), ('VALIDATED', 'Validated'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('rows_ready', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('error_summary', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField()),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('row_status', models.CharField(choices=[('OK', 'Ready'), ('WARNING', 'Ready, with a note'), ('ERROR', 'Blocked')], max_length=8)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='documents.importbatch')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_row', to='documents.document')),
            ],
            options={
                'ordering': ['batch', 'line_number'],
                'indexes': [models.Index(fields=['batch', 'row_status'], name='documents_i_batch_i_f2a04e_idx')],
            },
        ),
    ]
