# Generated by Django 5.2.12 on 2026-07-20 07:43

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_importbatch_importrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename_pattern', models.CharField(default='{TYPE}-{NUMBER}-{YEAR}.pdf', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Staged'), ('REVIEWED', 'Reviewed'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('staged_file', models.FileField(upload_to=documents.models.scan_stage_upload_path)),
                ('parsed_doc_type', models.CharField(blank=True, max_length=8)),
                ('parsed_number', models.PositiveIntegerField(blank=True, null=True)),
                ('parsed_series_year', models.PositiveIntegerField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED', 'No match'), ('CONFLICT', 'File already on record'), ('MANUAL', 'Picked by hand'), ('ATTACHED', 'Attached'), ('SKIPPED', 'Skipped')], max_length=10)),
                ('resolution', models.CharField(blank=True, max_length=10)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.scanbatch')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_file', to='documents.document')),
            ],
            options={
                'ordering': ['batch', 'original_filename'],
            },
        ),
    ]
